export { default as Home } from './Home/Home'
export { default as ContactUs } from './ContactUs/ContactUs'
export { default as ReviewMessage } from './ReviewMessage/ReviewMessage'
export { default as News } from './News/News'
export { default as NotFound } from './NotFound/NotFound'